language: python

# sudo false implies containerized builds, so we can use cacheing
sudo: false

os:
  - linux
  - osx

python:
  - 2.7

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/megaman
    - CONDA_CHANNEL="https://conda.anaconda.org/jakevdp"
  matrix:
    - CONDA_DEPS="pip nose coverage cython numpy scipy scikit-learn flann pyamg" PIP_DEPS="pyflann coveralls"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda install -c $CONDA_CHANNEL python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- travis_retry pip install $PIP_DEPS

install:
- python setup.py install --record installed_files.txt

script:
- mkdir -p $TEST_DIR
- cd $TEST_DIR && nosetests -v --with-coverage --cover-package=megaman megaman

after_success:
- coveralls

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
- conda clean --tarballs --packages --index-cache
- rm -rf $HOME/miniconda/pkgs/cache
- xargs rm <installed_files.txt

cache:
  directories:
    - $HOME/miniconda
